### ISSUE TITLE
License renewal

### ISSUE THREAD

**Issue by Flocap** [NextronSystems/aurora-agent-lite#11]
Hi, 

Not sure this is the correct place to report, but I did not get email after license expiration.
I think I'm still subscribed to the news letter, but my license expired 12/04 and did not get the new download link (spam folder checked). 

Regards.

**Comment by Neo23x0** [comment]
Some mail gateways are currently blocking the subscription emails. (e.g. Gmail does that)
Try to use a different email address (company email).

**Comment by Flocap** [comment]
Switched to another email, can close, thank you!
