### ISSUE TITLE
Download Aurora Agent Lite for Windows blocked by BITDEFENDER 

### ISSUE THREAD

**Issue by nightbird2021** [NextronSystems/aurora-agent-lite#12]
Hello,

When downloading Aurora Lite from nextron-systems.com Bitdefender Total security detected as dangerous and blocked the aurora-agent-lite-win-pack.zip installation files.

C:\Users\xxx\Downloads\aurora-agent-lite-win-pack.zip attempted to load a malicious resource detected as Amsi.Edge.22.87AF370A and was blocked. Your device is safe.

Is it useful/advisable to install Aurora Agent Lite in addition to an antivirus to detect possible security compromises?
My goal is to learn how to use an EDR.

THANKS

Good day

**Comment by nasbench** [comment]
Hi @nightbird2021

That detection by Bitdefender (and sometimes other AV) comes from the fact that Aurora-lite contains the detection rules (Sigma) in clear text. These rules might contain some strings that an AV might think are malicious (its usually 1 or 2 powershell rules).

Aurora is meant to be installed along side an AV as its job is not to replace an AV but to provide a larger coverage for certain type of attacks that an AV isn't designed to alert or trigger on.

If you can provide the file that windows defender triggered on perhaps we can try to mitigate it.

**Comment by nasbench** [comment]
Additional info could be found here https://github.com/SigmaHQ/sigma/issues/4925

Closing this issue as resolved for now. Please feel free to re-open in case of additional questions
