### ISSUE TITLE
Error when submitting form on Nextron Systems Aurora download page

### ISSUE THREAD

**Issue by alexanderkazanski** [NextronSystems/aurora-agent-lite#15]
**Description:** I’m experiencing an issue when trying to download Aurora Light from Nextron Systems Aurora. After filling out the form and pressing submit, the form refreshes without any confirmation.

**Steps to Reproduce:**

1. Go to Nextron Systems Aurora.
2. Fill out the download form.
3. Press the submit button.
4. Expected Behavior: The form should submit successfully and provide a download link or confirmation message.

**Actual Behavior:** The form refreshes, and no confirmation is provided. The network tab in Edge/Firefox/Chrome shows the following error from the submit method:

`{"status":"sib_security","msg":"Invalid Token Provided."}`

**Browsers Tested:**
- Microsoft Edge
- Firefox
- Chrome

**Additional Information:**

- I have tried clearing the cache and cookies.
- The issue persists across multiple browsers.

**Comment by nasbench** [comment]
Thanks for reporting this @alexander-kazanski. I will look into it and report back

**Comment by nasbench** [comment]
@alexander-kazanski the issue should be fixed now. Please try again and let us know.
