### ISSUE TITLE
Aurora agent log field definitions

### ISSUE THREAD

**Issue by legoguy1000** [NextronSystems/aurora-agent-lite#2]
We're testing out the aurora agent lite and ingesting the logs from Windows event logs to elasticsearch via winlogbeat. We are working on creating an ingest pipeline to normalize the data as best we can to ECS but the manual doesn't specify anything with regards to the log fields. Anything u can provide would be great. Also the manual specifies that the event codes used by aurora logs are internal but doesn't specify what they mean and the differences between them. Anything on that would be great too.

**Comment by Neo23x0** [comment]
> normalize the data as best we can to ECS but the manual doesn't specify anything with regards to the log fields. Anything u can provide would be great.

I think I'd used the JSON output to a local log file and ingest that with filebeat OR send the logs as JSON directly to an Elastic via UDP or TCP. 

The fields depend on the ETW event data and that depends on the accessed ETW channels. I'm not sure if we can and want to provide a schema of fields per event type. It may differ over different Windows versions.  

> Also the manual specifies that the event codes used by aurora logs are internal but doesn't specify what they mean and the differences between them. Anything on that would be great too.

I think we can provide that. Could you see if there is a way to export that information for the manual? @secDre4mer

**Comment by secDre4mer** [comment]
I've added them: See https://aurora-agent-manual.nextron-systems.com/en/latest/usage/event-id-list.html.

**Comment by legoguy1000** [comment]
```
I think I'd used the JSON output to a local log file and ingest that with filebeat OR send the logs as JSON directly to an Elastic via UDP or TCP.
```
How are the logs different/better if using JSON file/TCP/udp from Windows event logs? Are the fields/keys the same just not windows eventy?

**Comment by Neo23x0** [comment]
It's already in Key/Value pairs. Do you get them in key/value pairs when you ingest the Aurora Logs from Eventlog via WinLogbeat?

**Comment by legoguy1000** [comment]
Yes it is in a Windows event log way 😁
