### ISSUE TITLE
Error during startup lite agent version 1.2.2

### ISSUE THREAD

**Issue by tondorland** [NextronSystems/aurora-agent-lite#20]
When starting Aurora lite I get:

Error: MODULE ApplyIOCs MESSAGE: Could not compile filename iocs ERROR: ïnvalid regular expression  \"$r516\": syntax error

(Version 1.2.2).

Any idea? 
Regards, Ton Dorland

**Comment by Neo23x0** [comment]
Strange. When I use the current signature set, I don't get that error. 
You should try running:
```
aurora-agent-util.exe upgrade
```

**Comment by tondorland** [comment]
Thanks for the quick reply. Indeed this fixed the issue.

Regards, Ton Dorland

Van: Florian Roth ***@***.***>
Verzonden: zaterdag 9 november 2024 08:36
Aan: NextronSystems/aurora-agent-lite ***@***.***>
CC: tondorland ***@***.***>; Author ***@***.***>
Onderwerp: Re: [NextronSystems/aurora-agent-lite] Error during startup lite agent version 1.2.2 (Issue #20)


Strange. When I use the current signature set, I don't get that error.
You should try running:

aurora-agent-util.exe upgrade
