### ISSUE TITLE
Scanner question

### ISSUE THREAD

**Issue by dr4lekhine** [NextronSystems/aurora-agent-lite#3]
Hi There,

Thank you for this project.

I´m beginning to play Aurora Lite. I ran the agent without installation, just:

**aurora-agent-64.exe**
https://aurora-agent-manual.nextron-systems.com/en/latest/usage/usage.html#run-aurora

However, I wanted to know if there a way to only run a scan to dig into past Windows Event Logs (to check Sigma-based event matching there), and also is there any way to get an HTML report (like THOR lite or LOKI).

Thanks in advance.

Regards.

**Comment by phantinuss** [comment]
> However, I wanted to know if there a way to only run a scan to dig into past Windows Event Logs (to check Sigma-based event matching there)

No, that's basically what THOR is doing. It is a feature you have to pay for. (See the scanner comparision [here](https://www.nextron-systems.com/thor-lite/)).
