### ISSUE TITLE
p/ amsibypass.b

### ISSUE THREAD

**Issue by la-Loup-Garou** [NextronSystems/aurora-agent-lite#7]
hey,

Any reason why lite version has p/ amsibypass.b with the down load ?

**Comment by nasbench** [comment]
Hi,

As the lite version have the rules in clear text, it seems that defender is flagging one of the rule (probably related to powershell) as an amsibypass.

Can you send a screenshot of the alert? Is it triggering on the zip or a specific file?

**Comment by la-Loup-Garou** [comment]
Hi<
Thanks for your quick response, it flagged an actual file ps/ amsibypass.b

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by nasbench** [comment]
Can you send me a screenshot of the alert? The filename that got flagged?

Anything would be helpful to get this resolved :)

**Comment by nasbench** [comment]
@BeeFphoreal is the issue resolved for you?

**Comment by nasbench** [comment]
Closing this as stale
