### ISSUE TITLE
Aurora License Issue

### ISSUE THREAD

**Issue by abdullah0899** [NextronSystems/aurora-agent-lite#9]
I have downloaded the lite version of Aurora EDR, but when I try to download the license file the server displays a "site can't be reached" error.
![image](https://github.com/NextronSystems/aurora-agent-lite/assets/162958636/9ed4cff6-768c-420e-8694-ab4ed9c4ddb0)

**Comment by nasbench** [comment]
That was a temporary error from the backend side it would seem. Should be working fine now.

Please try again and let us know.

**Comment by nasbench** [comment]
License retrieval seems to be working fine. Please reopen the issue if it persists for you.
